Collision and Trigger Event Systems
mrLegenius/LevEngine pull request #17
Opened 2023-12-14 12:07 UTC by NemkovYaroslav

2023-12-14 13:27 UTC, mrLegenius requested changes

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        m_IsCollisionEnterEnabled = true;
Я не понимаю для чего вот эти булки.

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +            m_CollisionEnterEntityBuffer.pop_back();
Ты перемудрил с коллбеками

2023-12-14 13:27 UTC, mrLegenius commented on Sandbox/src/FPSGame/Systems/CollisionHandleSystem.h
> +                    );
У тебя тут обрабатывается каждая пуля, у которой вызывается OnTriggerEnter, которая вообще то должна быть коллбеком и не должна вызываться ручками.

Короче огромный скам.

Я не знаю как ты к этому пришел, но подумай, стал бы так использовать этот код сам?

В моей голове это выглядит так:

```
for (entity)

  auto rigidbody;

  for rigidbody.GetAllTriggerEnterCollisions
    if collider.entity is enemy
        destroy enemy
    destroy bullet
```

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Physics/Physics.cpp
> +        auto& collisionEvents = App::Get().GetPhysics().m_CollisionEvents;
Это циклическая зависимость, Physics -> PhysicsUpdate -> Physics.
Попробуй от этого избавиться

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Physics/Physics.cpp
> +#include <wrl/internal.h>
Это для чего?

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        //Log::Debug("ACTOR MAP SIZE: {0}", App::Get().GetPhysics().m_ActorEntityMap.size());
Мусор

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Scene/Systems/Physics/RigidbodyInitSystem.h
> +}
Перенеси это в папку с физикой

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +            App::Get().GetPhysics().m_ActorEntityMap.insert(m_Actor);
Это точно валидный вызов?

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        App::Get().GetPhysics().m_ActorEntityMap.erase(rigidbody.GetActor());
Ты же и так делаешь это в DetachRigidbody

2023-12-14 13:27 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +
```
m_Actor = App::Get().GetPhysics().GetPhysics()->createRigidDynamic(initialPose); 
App::Get().GetPhysics().GetScene()->addActor(*(reinterpret_cast<physx::PxRigidDynamic*>(m_Actor)));
```
- это говнокод, извините.

Должно быть:
`m_Actor = App::Get().GetPhysics().CreateDynamic(initialPose) `
в котором добавление в мапу происходит.

то же самое с детач ригидбоди

2023-12-14 13:39 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Physics.cpp
> +    void PhysicsUpdate::OneMoreStrangeSystem(entt::registry& registry)
Исправил

2023-12-14 13:44 UTC, NemkovYaroslav commented on Sandbox/resources/Scenes/TestScene.scene
> -      Intensity: 15.1000004
Не надо мне тут. В прошлый раз не моих рук было дело. Работал в Sandbox, нужно было закоммитить.

2023-12-15 09:52 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Collision.h
> +        //Vector3<int> ContactSecondColliderMaterialIndices;
Исправил

2023-12-21 07:00 UTC, mrLegenius requested changes

2023-12-21 10:40 UTC, merged