Feature/nav mesh building
mrLegenius/LevEngine pull request #22
Opened 2023-12-30 18:41 UTC by mordekayo

2023-12-31 10:01 UTC, mrLegenius requested changes

2023-12-31 10:01 UTC, mrLegenius commented on LevEngine/src/Scene/Components/NavMesh/NavMeshableComponent.h
> +        SAMPLE_POLYFLAGS_ALL		= 0xffff	// All abilities.
в этих двух енамах тоже бы поправить стиль

2024-01-04 20:10 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshableComponent.h
> +        SAMPLE_POLYFLAGS_ALL		= 0xffff	// All abilities.
Поправил

2024-01-04 20:10 UTC, mordekayo commented on Sandbox/resources/Models/Cube obj.obj
> +mtllib Cube obj.mtl
Удалил

2024-01-04 20:10 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.h
> +        int PartitionType = 0;
Исправил

2024-01-04 20:10 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.h
> +        SAMPLE_PARTITION_WATERSHED = 0,
Исправил. А насчёт настроек пока сам не понимаю. Это какие то типы обработки графа, но человеческого объяснения я не нашёл, и как понял почти всегда юзается дефолтное. Если пойму отпишу

2024-01-04 20:10 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +					Log::Trace("Build navigation: Could not build distance field.");
Исправил

2024-01-04 20:10 UTC, mordekayo commented on LevEditor/src/ComponentDebugRenderers/NavMeshDebugRenderer.cpp
> +                    if ((p[nvp + j] & 0x8000) == 0) continue;
Исправил

2024-01-04 20:10 UTC, mordekayo commented on LevEditor/src/ComponentDebugRenderers/NavMeshDebugRenderer.cpp
> +                        points[k] = DirectX::SimpleMath::Vector3(x, y, z);
Исправил

2024-01-04 20:10 UTC, mordekayo commented on LevEditor/src/ComponentDebugRenderers/NavMeshDebugRenderer.cpp
> +                    if (p[nvp + j] & 0x8000) continue;
Исправил

2024-01-04 20:10 UTC, mordekayo commented on LevEditor/LevEditor.vcxproj
> +      <RuntimeLibrary>MultiThreadedDebugDll</RuntimeLibrary>
Уверен? Без них LevEditor не загружается

2024-01-05 08:23 UTC, mrLegenius commented on LevEditor/LevEditor.vcxproj
> +      <RuntimeLibrary>MultiThreadedDebugDll</RuntimeLibrary>
Уверен. Должно запускаться, уже раз 5 точно проходили

2024-01-06 09:38 UTC, mordekayo commented on LevEditor/LevEditor.vcxproj
> +      <RuntimeLibrary>MultiThreadedDebugDll</RuntimeLibrary>
Убрал

2024-01-06 09:39 UTC, mordekayo commented on LevEditor/src/ComponentDebugRenderers/NavMeshDebugRenderer.cpp
> +                    DirectX::SimpleMath::Vector3 points[2];
Исправил

2024-01-06 09:39 UTC, mordekayo commented on LevEditor/src/ComponentDebugRenderers/NavMeshDebugRenderer.cpp
> +                        points[k] = DirectX::SimpleMath::Vector3(x, y, z);
Исправил

2024-01-06 09:39 UTC, mordekayo commented on LevEditor/src/GUI/Drawers/Components/NavMeshComponentDrawer.cpp
> +            }
Сделал комбобокс

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/LevEngine.vcxproj
> +      <AdditionalDependencies>assimp-vc143-mt.lib;fmodstudioL_vc.lib;fmodL_vc.lib;PhysXCommon_64.lib;PhysX_64.lib;PhysXFoundation_64.lib;PhysXExtensions_static_64.lib;PhysXPvdSDK_static_64.lib;lua54.
Исправил

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +#include "PxRigidBody.h"
Убрал

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +		const auto& thisEntity = selfView.begin();
Теперь кеширую энтити на on construct

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +		if(rigidBody.GetColliderType() != Collider::Type::Box)
Сделал компонент отдельный

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +			const auto& mesh = meshRendererComponent.mesh->GetMesh();
Проверку добавил

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +            Log::Trace("Build navigation: Could not allocate heightfield.");
Сделал

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +            Log::Trace("Build navigation: Out of memory 'm_TriAreas'", trianglesCount);
Сделал

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +            Log::Trace("Build navigation: Could not rasterize triangles.");
Сделал

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +			Log::Trace("Build navigation: Out of memory 'CompactHeightField'.");
Сделал

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +            Log::Trace("Build navigation: Could not create solid heightfield.");
Сделал

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +			Log::Trace("Build navigation: Could not build compact data.");
Сделал

2024-01-06 09:39 UTC, mordekayo commented on LevEngine/src/Scene/Components/NavMesh/NavMeshComponent.cpp
> +			Log::Trace("Build navigation: Could not erode.");
Сделал

2024-01-06 10:10 UTC, merged