Feature/skeletal animation
mrLegenius/LevEngine pull request #29
Opened 2024-01-12 08:17 UTC by Fenrir7Asteron

2024-01-15 07:41 UTC, mrLegenius requested changes

2024-01-15 07:41 UTC, mrLegenius commented on LevEditor/LevResources/Shaders/CascadeShadowPass.hlsl
> +	output.pos = mul(pos, model);
А если костей нет, то все ок будет?

2024-01-15 07:41 UTC, mrLegenius commented on LevEditor/src/GUI/Drawers/Assets/AnimationAssetDrawer.cpp
> +        [[nodiscard]] String GetLabel() const override { return "AnimationAsset"; }
```suggestion
        [[nodiscard]] String GetLabel() const override { return "Animation"; }
```

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Assets/AnimationAsset.h
> +		explicit AnimationAsset(const Path& path, const UUID uuid) : Asset(path, uuid)
```suggestion
		explicit AnimationAsset(const Path& path, const UUID uuid) : Asset(path, uuid), m_AnimationIdx(-1)
```
+ вынеси в .cpp

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Assets/AssetDatabase.cpp
> +			}
А что, try catch не справляется с ошибкой, когда файла нет?

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Assets/Asset.h
> +    	Asset() = default;
Так, а это для чего?

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Assets/MeshAsset.cpp
> +            }
Сделай отдельный метод для этого и вызывай его здесь.

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Assets/MeshAsset.cpp
> +            Log::CoreWarning("Failed to load animations in {0}. Error: {1}", m_Path.string(), e.what());
Но меш же тут тоже может не загрузиться. 
Должны быть отдельные методы для загрузки меша и анимаций.

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Assets/MeshAsset.h
> +	class MeshAsset final : public Asset, public eastl::enable_shared_from_this<MeshAsset>
Это для чего тут?

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Platform/D3D11/D3D11VertexBuffer.cpp
> +}
Просто дупликат метода выше.
Можно сделать один приватный, который принимает void* 
А из этих передавать туда

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Renderer/3D/Animator.cpp
> +			m_CurrentTime = fmod(m_CurrentTime, m_CurrentAnimation->GetDuration());
опа, соскучился по звуку? Ха-ха

2024-01-15 07:41 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Animation/AnimatorComponent.h
> +        [[nodiscard]] eastl::array<Matrix, AnimationConstants::MaxBoneCount> GetFinalBoneMatrices() const;
```suggestion
        [[nodiscard]] Array<Matrix, AnimationConstants::MaxBoneCount> GetFinalBoneMatrices() const;
```

2024-01-15 08:22 UTC, mrLegenius requested changes

2024-01-15 08:22 UTC, mrLegenius commented on LevEngine/src/Assets/AssetDatabase.cpp
> +	}
У нас уже есть метод CreateNewAsset

2024-01-16 06:05 UTC, Fenrir7Asteron commented on LevEditor/LevResources/Shaders/CascadeShadowPass.hlsl
> +	output.pos = mul(pos, model);
Рендеринг не ломается, на производительность вроде бы тоже никак не влияет. В целом, можно конечно отдельные шейдеры выделить под анимированные меши, но это будет просто неудобно несколько почти одинаковых шейдеров держать. Вот если бы добавить поддержку флагов, чтобы в шейдере #if SKELETAL_MESH использовать...

2024-01-16 06:24 UTC, Fenrir7Asteron commented on LevEngine/src/Renderer/3D/Animator.cpp
> +			m_CurrentTime = fmod(m_CurrentTime, m_CurrentAnimation->GetDuration());
Фить-ха!

2024-01-16 06:31 UTC, Fenrir7Asteron commented on LevEngine/src/Assets/AssetDatabase.cpp
> +	}
Может его переименовть в CreateAsset? Я его и не заметил, потому что он по другому называется (наверное).

2024-01-16 06:56 UTC, Fenrir7Asteron commented on LevEditor/src/GUI/Drawers/Assets/AnimationAssetDrawer.cpp
> +        [[nodiscard]] String GetLabel() const override { return "AnimationAsset"; }
Пофиксил.

2024-01-16 06:56 UTC, Fenrir7Asteron commented on LevEngine/src/Assets/AnimationAsset.h
> +		explicit AnimationAsset(const Path& path, const UUID uuid) : Asset(path, uuid)
Пофиксил.

2024-01-16 06:57 UTC, Fenrir7Asteron commented on LevEngine/src/Assets/Asset.h
> +    	Asset() = default;
Уже не помню. Убрал, ничего не сломалось.

2024-01-16 07:24 UTC, Fenrir7Asteron commented on LevEngine/src/Assets/MeshAsset.cpp
> +            }
Вынес выставление полей в метод AnimationAsset::Init

2024-01-16 07:30 UTC, Fenrir7Asteron commented on LevEngine/src/Assets/MeshAsset.h
> +	class MeshAsset final : public Asset, public eastl::enable_shared_from_this<MeshAsset>
Чтобы я мог получить shared_ptr на MeshAsset и сохранить его в AnimationAsset. MeshAsset мне нужен, чтобы получать путь fbx файла, откуда мне нужно ассимпом парсить анимации при десериализации AnimationAsset. AnimationAsset же отдельным файлом лежит. И вот чтобы знать путь до fbx, но сохранять ассет, а не просто путь (который может и поменяться), я вот эту штуку использую.

2024-01-16 07:31 UTC, Fenrir7Asteron commented on LevEngine/src/Assets/MeshAsset.cpp
> +            Log::CoreWarning("Failed to load animations in {0}. Error: {1}", m_Path.string(), e.what());
Вынес загрузку анимаций в отдельный метод.

2024-01-16 07:31 UTC, Fenrir7Asteron commented on LevEngine/src/Platform/D3D11/D3D11VertexBuffer.cpp
> +}
Поправил.

2024-01-16 07:31 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Animation/AnimatorComponent.h
> +        [[nodiscard]] eastl::array<Matrix, AnimationConstants::MaxBoneCount> GetFinalBoneMatrices() const;
Поправил.

2024-01-16 07:31 UTC, Fenrir7Asteron commented on LevEngine/src/Assets/AssetDatabase.cpp
> +	}
Свой метод дубликат убрал.

2024-01-16 08:38 UTC, mrLegenius commented on LevEngine/src/Assets/AssetDatabase.cpp
> +	}
Ну тут разная логика. CreateAsset - просто создать ассет из существующего класса.
CreateNewAsset - прям файл ассета создает.
Можно попробовать переименовать в CreateAssetFile или чет такое.

2024-01-16 18:13 UTC, merged