Feature/fmod integration
mrLegenius/LevEngine pull request #6
Opened 2023-10-19 19:42 UTC by Fenrir7Asteron

2023-10-20 07:54 UTC, Harrm commented on LevEngine/src/FMOD/LevFmod.cpp
> +        if (m_Listeners.size() == 0) {
```suggestion
        if (m_Listeners.empty()) {
```

2023-10-20 07:56 UTC, Harrm commented on LevEngine/src/FMOD/LevFmod.cpp
> +        if (!m_EventDescriptions.count(eventPath)) {
You make two lookups instead of one. You can get an iterator, check if it's != end, and use it below if it's not.

2023-10-20 07:57 UTC, Harrm commented on LevEngine/src/FMOD/LevFmod.cpp
> +            const auto instanceId = reinterpret_cast<uint64_t>(instance);
Use intptr_t.

2023-10-20 08:01 UTC, Harrm commented on LevEngine/src/FMOD/LevFmod.h
> +#include "../Kernel/Logger.h"
Don't use relative paths.

2023-10-20 08:02 UTC, Harrm commented on LevEngine/src/FMOD/LevFmod.h
> +        inline int CheckErrors(FMOD_RESULT result) const
Methods are inline by default.

2023-10-20 08:02 UTC, Harrm commented on LevEngine/src/FMOD/LevFmod.h
> +                Log::Error(err);
Use logger's formatting capabilities, they are much more effective.

2023-10-20 08:03 UTC, Harrm commented on LevEngine/src/FMOD/LevFmod.h
> +        Vector<AudioListenerComponent*> m_Listeners;
Why are they stored as raw pointers? And all the stuff above.

2023-10-20 08:03 UTC, Harrm commented on LevEngine/src/Kernel/Application.cpp
> +	m_Fmod->Init(1024, FMOD_STUDIO_INIT_LIVEUPDATE, FMOD_INIT_VOL0_BECOMES_VIRTUAL);
Give a name to the magic number.

2023-10-20 08:04 UTC, Harrm commented on LevEngine/src/Scene/Components/Audio/AudioListener.h
> +        bool listenerLock = false;
Comments are appreciated.

2023-10-20 08:06 UTC, Harrm commented on LevEngine/src/Scene/Components/Audio/AudioSource.h
> +        bool isOneShot{};
Why does it have public fields if it's not a POD structure?

2023-10-20 08:28 UTC, mrLegenius requested changes

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +        String bankStringsPath = bankFilePath + ".strings.bank";
Этим компонент явно не должен заниматься.
Перемести в класс аудио

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +        return this->playOnInit;
Давай без this

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +        this->playOnInit = playOnInit;
Везде

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +                component.eventName = node["AudioEventName"].as<eastl::string>();
`.as<String>(); `
 используем только наши типы

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +            if (node["AudioBank"])
if (const auto audioBank = node["AudioBank"])
    component.audioBank = DeserializeAsset<AudioBankAsset>(audioBank);
    
   внизу тож самое

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioSource.h
> +        bool playOnInit{};
Публичные поля с большой буквы.

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/Scene/Scene.cpp
> +entt::registry& Scene::GetRegistry()
Без этого метода давай сделаем

2023-10-20 08:28 UTC, mrLegenius commented on Sandbox/src/FPSGame/Systems/ShootSystem.h
> +        Application::Get().GetAudioSubsystem()->PlayOneShot("event:/ProjectileHit", entity);
Чет мне не оч заходит "event:/" везде писать

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioSource.h
> +    struct AudioSourceComponent
Как-то слишком много логики в компоненте

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/FMOD/LevFmod.cpp
> +        for (int i = 0; i < m_Listeners.size(); i++) {
foreach не пойдет?

2023-10-20 08:28 UTC, mrLegenius commented on LevEngine/src/FMOD/LevFmod.cpp
> +        if (instance) {
Давай одним стилем скобок пользоваться
По нашему код стайлу 
```
if (instance)
{
   if (playOnCreate)
       PlaySound(instance);
}
```

2023-10-20 08:28 UTC, mrLegenius commented on Sandbox/src/FPSGame/FPSGame.cpp
> +#include <Scene/Systems/Audio/AudioSourceInitSystem.h>
В игре не должно быть инклюдов движка, кроме LevEngine.h

2023-10-21 08:10 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +        Vector<AudioListenerComponent*> m_Listeners;
Он какие-то ошибки кидал, когда я делал их shared_ptr, и я забил.

2023-10-21 08:25 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.h
> +        bool isOneShot{};
Почему нет?

2023-10-21 10:19 UTC, Fenrir7Asteron commented on LevEditor/src/EditorLayer.cpp
> +        auto& registry = scene->GetRegistry();
В эдиторе конструктор сцены вызывается в эдит моде, и в это время мне не нужно, чтобы звуки играли. И ещё при переходе в плей мод конструктор сцены не вызывается. Не понял предложение.

2023-10-21 10:26 UTC, Fenrir7Asteron commented on LevEditor/src/EditorLayer.cpp
> +#include <Scene/Components/Audio/AudioSource.h>
Вижуалка при автодополнении с угловыми скобочками вставляет. Что-то не могу найти, можно ли перенастроить на "".

2023-10-21 10:27 UTC, Fenrir7Asteron commented on LevEditor/src/GUI/Drawers/Assets/AudioBankAssetDrawer.cpp
> +        [[nodiscard]] String GetLabel() const override { return "AudioBankAsset"; }
Но у всех других ассетов есть приписка Asset...

2023-10-21 10:55 UTC, Fenrir7Asteron commented on Sandbox/src/FPSGame/Systems/ShootSystem.h
> +        Application::Get().GetAudioSubsystem()->PlayOneShot("event:/ProjectileHit", entity);
Мне тоже не заходило, а потом я увидел, что из фмода когда копируешь имя эвента, он тебе его копирует вместе с этим префиксом, так что получается удобно. Не приходится его каждый раз стирать.

2023-10-21 10:56 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.h
> +    struct AudioSourceComponent
Если сделаю отдельный класс что-то вроде AudioPlayer с логикой проигрывания, и компонент будет содержать ссылку на него, то лучше?

2023-10-21 10:58 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.cpp
> +        for (int i = 0; i < m_Listeners.size(); i++) {
Не пойдёт, в фмод нужно передавать по индексу listener.

2023-10-24 20:23 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.cpp
> +        if (m_Listeners.size() == 0) {
Поправил.

2023-10-24 20:23 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.cpp
> +        if (!m_EventDescriptions.count(eventPath)) {
Поправил.

2023-10-24 20:23 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.cpp
> +            const auto instanceId = reinterpret_cast<uint64_t>(instance);
Поправил.

2023-10-24 20:23 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +#include "../Kernel/Logger.h"
Поправил.

2023-10-24 20:24 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +        ~LevFmod();
Сделал класс final.

2023-10-24 20:24 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +        inline int CheckErrors(FMOD_RESULT result) const
Убрал inline.

2023-10-24 20:24 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +                Log::Error(err);
Поправил.

2023-10-24 20:25 UTC, Fenrir7Asteron commented on LevEngine/src/Kernel/Application.cpp
> +	m_Fmod->Init(1024, FMOD_STUDIO_INIT_LIVEUPDATE, FMOD_INIT_VOL0_BECOMES_VIRTUAL);
Поправил.

2023-10-24 20:29 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioListener.h
> +        bool listenerLock = false;
listenerLock убрал, так как в итоге я его не использовал.

2023-10-24 20:30 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.h
> +        bool isOneShot{};
Утащил поля в отдельный класс AudioPlayer и сделал их приватными.

2023-10-24 20:31 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/SceneManager.cpp
> +    // TODO: Create PreSceneLoad event and release audio there
Больше не актуально, так как теперь инстанс фмода хранится не в Application, а прямо в Scene.

2023-10-24 20:32 UTC, Fenrir7Asteron commented on FMODStudio/FMODStudio.vcxproj
> +(xcopy /y /d "$(SolutionDir)$(ProjectName)\core\lib\$(Platform)\fmod*.lib" "$(OutDir)")
Убрал копирование, добавил их как доп либы в настройки проекта LevEngine.

2023-10-24 20:33 UTC, Fenrir7Asteron commented on LevEditor/src/EditorLayer.cpp
> +#include <Scene/Components/Audio/AudioSource.h>
Поправил везде угловые скобки на ""

2023-10-24 20:33 UTC, Fenrir7Asteron commented on LevEditor/src/GUI/Drawers/Assets/AudioBankAssetDrawer.cpp
> +        [[nodiscard]] String GetLabel() const override { return "AudioBankAsset"; }
Сделал просто "AudioBank"

2023-10-24 20:34 UTC, Fenrir7Asteron commented on LevEditor/src/GUI/Drawers/Components/AudioSourceComponentDrawer.cpp
> +            auto& eventName = component.eventName;
Нет, не меняет, оказывается. ) У меня из-за этого оно только при выходе и повторном входе в плэй мод обновляло имя. Сделал через буффер.

2023-10-24 20:34 UTC, Fenrir7Asteron commented on Sandbox/src/FPSGame/Systems/ShootSystem.h
> +        Application::Get().GetAudioSubsystem()->PlayOneShot("event:/ProjectileHit", entity);
Добавил в логику проигрывания, чтобы он сам дописывал event:/, если его не хватает. Так что теперь и с префиксом и без можно писать.

2023-10-24 20:34 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.h
> +    struct AudioSourceComponent
Унёс в класс AudioPlayer.

2023-10-24 20:36 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.cpp
> +        if (instance) {
```
Привёл скобки к единому виду
if (instance)
{
   if (playOnCreate)
   {
      PlaySound(instance);
   }
}
```

2023-10-24 20:36 UTC, Fenrir7Asteron commented on Sandbox/src/FPSGame/FPSGame.cpp
> +#include <Scene/Systems/Audio/AudioSourceInitSystem.h>
Поправил.

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/AudioPlayer.cpp
> +#pragma region Getters
Мне не нравится такая сортировка.
Лучше логически связывать.
Геттер - Сеттер
Геттер - Сеттер

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioListener.cpp
> +			return;
Таб лишний?
И как я уже говорил - можно без скобок и в одну строчку такую конструкцию 
`if (IsInitialized()) return;`

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Scene/Components/Audio/AudioListener.cpp
> +	void AudioListenerComponent::OnComponentConstruct(entt::registry& registry, entt::entity entity)
Все таки мне не нравятся эти методы здесь.
Лучше их перенести в LevFmod, чтобы логика шла от общего к частному.

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/LevFmod.h
> +    class LevFmod final
Давай переименуем этот класс в LevAudio или просто Audio. 
Чтобы было более абстрактно => проще

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/LevFmod.h
> +}
Вот эти ворвард декларации под один неймсепс + убери DirectX/SimpleMath чтобы вообще о нем упоминания не было в коде.

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/LevFmod.cpp
> +            Log::Info("FMOD Sound System: Successfully initialized");
CoreInfo и ниже еще CoreError. В общем в движке весь CoreLogging используем

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/LevFmod.cpp
> +        if (m_Listeners.size() == FMOD_MAX_LISTENERS)
Предпочитаю >=, потому что всякое может быть

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/LevFmod.cpp
> +            Log::Warning("FMOD Sound System: Tried to remove an unknown listener.");
Тут не нужен return?

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/LevFmod.cpp
> +            intptr_t instanceHandle = reinterpret_cast<intptr_t>(instance);
c intptr_t хорошо сделано, но я бы еще предложил завернуть это в более говорящий юзинг (тайпдеф)
например SoundHandler

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/LevFmod.cpp
> +    FMOD_VECTOR LevFmod::ToFmodVector(const DirectX::SimpleMath::Vector3 vec)
Убери отсюда `DirectX::SimpleMath:: `. Используем чистый Vector3 из Math/Vector3.h

2023-10-25 18:55 UTC, mrLegenius commented on LevEngine/src/Audio/LevFmod.cpp
> +    float LevFmod::GetGlobalParameterByName(const String& parameterName) {
Тут и ниже стайл скобочек поправить

2023-10-31 15:19 UTC, Fenrir7Asteron commented on LevEngine/src/Assets/AssetDatabase.h
> +			const String pathString = ToString(path);
Потому что у строковых банков двойной экстеншн bankName.strings.bank. path.extension() находит только последнее расширение, а мне оба надо.

2023-10-31 16:02 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioListener.h
> +        Ref<LevFmod> m_Fmod;
Теперь нет, теперь он привязан к сцене.

2023-11-02 16:11 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/SceneManager.cpp
> +    // TODO: Create PreSceneLoad event and release audio there
Теперь выгружаю аудио в Scene::CleanupScene

2023-11-02 16:12 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +}
Поправил.

2023-11-02 16:12 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +    class LevFmod
Поправил.

2023-11-02 16:12 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +        FMOD_VECTOR ToFmodVector(DirectX::SimpleMath::Vector3 vec);
Поправил.

2023-11-02 16:12 UTC, Fenrir7Asteron commented on LevEngine/src/FMOD/LevFmod.h
> +                Log::Error(err);
Поправил.

2023-11-02 16:14 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +    void AudioSourceComponent::OnComponentConstruct(entt::registry& registry, entt::entity entity)
Поправил.

2023-11-02 16:14 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +            String eventNameWithPrefix = String("event:/") + eventName;
Поправил.

2023-11-02 16:14 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +            if (!entity)
Поправил.

2023-11-02 16:14 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +        if (IsInitialized())
Поправил.

2023-11-02 16:15 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +        String bankStringsPath = bankFilePath + ".strings.bank";
Поправил.

2023-11-02 16:15 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +        return this->playOnInit;
Поправил.

2023-11-02 16:15 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +        this->playOnInit = playOnInit;
Поправил.

2023-11-02 16:15 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +                component.eventName = node["AudioEventName"].as<eastl::string>();
Поправил.

2023-11-02 16:16 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.cpp
> +            if (node["AudioBank"])
Поправил. Чтобы работало добавил перегрузку.
`Ref<T> DeserializeAsset(const YAML::Node& node)`

2023-11-02 16:16 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioSource.h
> +        bool playOnInit{};
Поправил.

2023-11-02 16:17 UTC, Fenrir7Asteron commented on LevEngine/src/Audio/AudioPlayer.cpp
> +#pragma region Getters
Поправил.

2023-11-02 16:17 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioListener.cpp
> +			return;
Поправил.

2023-11-02 16:18 UTC, Fenrir7Asteron commented on LevEngine/src/Scene/Components/Audio/AudioListener.cpp
> +	void AudioListenerComponent::OnComponentConstruct(entt::registry& registry, entt::entity entity)
Менять не стал. OnConstruct и OnDestroy компонентов логичнее делать в компонентах.

2023-11-02 16:18 UTC, Fenrir7Asteron commented on LevEngine/src/Audio/LevFmod.h
> +}
Поправил.

2023-11-02 16:19 UTC, Fenrir7Asteron commented on LevEngine/src/Audio/LevFmod.cpp
> +            Log::Info("FMOD Sound System: Successfully initialized");
Поправил.

2023-11-02 16:19 UTC, Fenrir7Asteron commented on LevEngine/src/Audio/LevFmod.cpp
> +        if (m_Listeners.size() == FMOD_MAX_LISTENERS)
Поддердживаю, тоже так обычно делаю, но тут что-то не сделал сразу. Поправил.

2023-11-02 16:20 UTC, Fenrir7Asteron commented on LevEngine/src/Audio/LevFmod.cpp
> +            Log::Warning("FMOD Sound System: Tried to remove an unknown listener.");
А ты хорош. Поправил.

2023-11-02 16:20 UTC, Fenrir7Asteron commented on LevEngine/src/Audio/LevFmod.cpp
> +            intptr_t instanceHandle = reinterpret_cast<intptr_t>(instance);
Добавил 
`typedef intptr_t EventInstanceHandle;`

2023-11-02 16:20 UTC, Fenrir7Asteron commented on LevEngine/src/Audio/LevFmod.cpp
> +    FMOD_VECTOR LevFmod::ToFmodVector(const DirectX::SimpleMath::Vector3 vec)
Поправил.

2023-11-02 17:42 UTC, merged