PhysX Physics
mrLegenius/LevEngine pull request #9
Opened 2023-11-22 16:50 UTC by NemkovYaroslav

2023-11-23 06:57 UTC, mrLegenius requested changes

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        }
Этот свитч = ApplyTransformScale. Замени на вызов функции

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +            DetachCollider();
Не очень хорошо отцеплять коллайдер в таком случае.
Лучше кинуть Warning и выйти из метода ничего не сделав. 
Только не забудь в таком случае переместить присваивание типа коллайдера ниже

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +    int Rigidbody::GetColliderNumber() const
Переименуй в GetColliderCount как принято в айти мире

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (radius <= 0.0f || radius >= FLT_MAX) return;
Как float может быть больше чем максимальное значение float?

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (halfHeight < 0.0f || halfHeight >= FLT_MAX) return;
и тут

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if ((halfExtents.x <= 0.0f || halfExtents.x >= FLT_MAX) || (halfExtents.y <= 0.0f || halfExtents.y >= FLT_MAX) || (halfExtents.z <= 0.0f || halfExtents.z >= FLT_MAX)) return;
и тут

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (staticFriction < 0.0f || staticFriction > FLT_MAX) return;
и тут

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (dynamicFriction < 0.0f || dynamicFriction > FLT_MAX) return;
и тут

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (restitution < 0.0f || restitution > 1.0f) return;
и тут

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        void SetRestitution(const float restitution);
Вот эти все методы бы в коллайдеры перенести, так как им пренадлежит

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        [[nodiscard]] PxMaterial* GetPhysicalMaterials(const PxShape* colliders) const;
Мне не оч нравится, что это тут находится. Но если по другому сложно, то забей

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Physics.h
> +    using namespace physx;
убери отсюда using

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Physics.h
> +        [[nodiscard]] static Physics& GetInstance();
Давай короч по другому.

Создавай этот `Physics `в `Application`. `Scope<Physics> m_Physics;`
Там создай метод
`Physics& Physics() const { return  *m_Physics; }`

Обращаться можно будет так: App::Physics().Something

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Physics/Physics.h
> +        void Deinitialize();
что за деинициализация, давай нормально какой-нить Reset или Cleanup

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Renderer/DebugRender/DebugRender.cpp
> +    void DebugRender::DrawWireCube(Vector3 position, Vector3 size, Color color)
Ты зачем тут const убрал

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Renderer/DebugRender/DebugRender.cpp
> +    void DebugRender::DrawWireCube(Matrix model, const Color color)
const Matrix model

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Scene/Serializers/SceneSerializer.cpp
> +#include "Physics/Components/Rigidbody.h"
Это тут не обязательно видимо

2023-11-23 06:57 UTC, mrLegenius commented on LevEngine/src/Scene/Systems/Physics/RigidbodyUpdateSystem.cpp
> +    }
Забавно, ты просто кешируешь скейл от ВСЕХ ентити и проверяешь для каждого. 
Тут оставь просто:
```
for (const auto entity : view)
        {
            auto [rigidbody, transform] = view.get<Rigidbody, Transform>(entity);
            rigidbody.SetTransformScale(transform.GetWorldScale());
        }
```
А проверку сделай в самом компоненте

2023-11-23 06:57 UTC, mrLegenius commented on Sandbox/Sandbox.levproject
> +StartScene: resources\Scenes\PhysicsTestScene.scene
Это не надо коммитить было

2023-11-23 06:57 UTC, mrLegenius commented on Sandbox/src/Sandbox.cpp
> +		: Application({ "Sandbox", 1200, 1200, args})
Это тоже не надо было коммитить

2023-11-23 07:52 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +#include "Physics/Components/Rigidbody.h"
В LevEngine.h вижу только старую физику

2023-11-23 09:13 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +            transform.ForceRecalculateModel();
Убрал

2023-11-23 09:13 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +            Matrix parent =
Переименовал

2023-11-23 09:13 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +            const float maxScale = std::max(transformScale.x, std::max(transformScale.y, transformScale.z));
Заменил

2023-11-23 09:14 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +            transform.ForceRecalculateModel();
Исправил

2023-11-23 09:14 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +            Matrix parent =
Исправил

2023-11-23 09:14 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +            const float maxScale = std::max(transformScale.x, std::max(transformScale.y, transformScale.z));
Исправил

2023-11-23 09:15 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +                    Matrix::CreateScale(component.GetSphereRadius() * maxScale)
Исправил

2023-11-23 09:29 UTC, NemkovYaroslav commented on LevEditor/src/ComponentDebugRenderers/RigidbodyDebugRenderer.cpp
> +#include "Physics/Components/Rigidbody.h"
Исправил

2023-11-23 09:31 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +    class PhysicsDrawer final : public ComponentDrawer<Rigidbody, PhysicsDrawer>
Исправил

2023-11-23 09:31 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +        [[nodiscard]] String GetLabel() const override { return "Physics"; }
Исправил

2023-11-23 11:32 UTC, NemkovYaroslav commented on LevEditor/src/EditorLayer.cpp
> +#include "Scene/Systems/Physics/RigidbodyUpdateSystem.h"
Исправил

2023-11-23 11:32 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +            if (ImGui::BeginCombo("Rigidbody Type", currentRigidbodyTypeString))
Исправил

2023-11-23 11:32 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +            if (currentRigidbodyTypeString == "DYNAMIC")
Исправил

2023-11-23 11:32 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +                if (ImGui::BeginCombo("Collider Type", currentColliderTypeString))
Исправил

2023-11-23 11:32 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +                if (currentColliderTypeString == "SPHERE")
Исправил

2023-11-23 12:01 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +    using namespace physx;
Исправил

2023-11-23 12:01 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        Vector<PhysicalMaterial> MaterialCollection { PhysicalMaterial() };
Исправил

2023-11-23 12:19 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +                EditorGUI::DrawFloatControl("Restitution", BindGetter(&Rigidbody::GetRestitution, &component), BindSetter(&Rigidbody::SetRestitution, &component), 1.0f, 0.0f, 1.0f);
Не совсем понял вопрос, но скажу: двигать getter'ы и setter'ы в специальную структурку пока не очень хочу. Чуть позже поправлю.

2023-11-23 12:19 UTC, NemkovYaroslav commented on LevEngine/LevEngine.vcxproj
> +      <RuntimeLibrary>MultiThreadedDebugDll</RuntimeLibrary>
Не понял откуда оно там взялось

2023-11-23 12:19 UTC, NemkovYaroslav commented on LevEngine/LevEngine.vcxproj
> +      <RuntimeLibrary>MultiThreadedDebugDll</RuntimeLibrary>
Не понял откуда оно там взялось

2023-11-23 12:20 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +    enum class ColliderType
Исправил

2023-11-23 12:44 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        bool GetInitializationFlag() const;
Исправил

2023-11-23 12:47 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        [[nodiscard]] bool GetRigidbodyGravityFlag() const;
Исправил

2023-11-23 12:48 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        PxRigidActor* m_Rigidbody = NULL;
Исправил

2023-11-23 12:49 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        bool m_IsRigidbodyGravityEnabled = true;;
Исправил

2023-11-23 12:49 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        RigidbodyType m_RigidbodyType = RigidbodyType::Dynamic;
Исправил

2023-11-23 16:08 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        ColliderType m_ColliderType = ColliderType::Box;
Исправил

2023-11-23 16:08 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        }
Исправил.

2023-11-23 16:59 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +            DetachCollider();
Вроде работает безотказно. В будущем эта проверка вовсе не пригодится. Из-за того, что переместил тип коллайдера внутрь m_ColliderCollection, установку типа коллайдера отправил в самый конец функции. Думаю, пока так оставить.

2023-11-23 17:00 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +            if (ImGui::BeginCombo("Rigidbody Type", currentRigidbodyTypeString))
Не могу, у меня там доп логика висит на edit и на runtime мод

2023-11-23 17:14 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +    int Rigidbody::GetColliderNumber() const
Исправил

2023-11-23 17:17 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (radius <= 0.0f || radius >= FLT_MAX) return;
Исправил

2023-11-23 17:17 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (halfHeight < 0.0f || halfHeight >= FLT_MAX) return;
Исправил

2023-11-23 17:17 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if ((halfExtents.x <= 0.0f || halfExtents.x >= FLT_MAX) || (halfExtents.y <= 0.0f || halfExtents.y >= FLT_MAX) || (halfExtents.z <= 0.0f || halfExtents.z >= FLT_MAX)) return;
Исправил

2023-11-23 17:17 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (staticFriction < 0.0f || staticFriction > FLT_MAX) return;
Исправил

2023-11-23 17:18 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +        if (restitution < 0.0f || restitution > 1.0f) return;
Тут всё окей

2023-11-23 17:19 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        [[nodiscard]] PxMaterial* GetPhysicalMaterials(const PxShape* colliders) const;
По-другому невозможно, эти методы для работы с physx.

2023-11-23 17:20 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Physics.h
> +    using namespace physx;
Исправил

2023-11-23 17:27 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Physics.h
> +        void Deinitialize();
Исправил

2023-11-23 17:35 UTC, NemkovYaroslav commented on LevEngine/src/Renderer/DebugRender/DebugRender.cpp
> +    void DebugRender::DrawWireCube(Vector3 position, Vector3 size, Color color)
Исправил

2023-11-23 17:40 UTC, NemkovYaroslav commented on LevEngine/src/Renderer/DebugRender/DebugRender.cpp
> +    void DebugRender::DrawWireCube(Matrix model, const Color color)
Может Matrix& model?

2023-11-23 17:40 UTC, NemkovYaroslav commented on LevEngine/src/Scene/Serializers/SceneSerializer.cpp
> +#include "Physics/Components/Rigidbody.h"
Исправил

2023-11-23 17:45 UTC, NemkovYaroslav commented on Sandbox/Sandbox.levproject
> +StartScene: resources\Scenes\PhysicsTestScene.scene
Исправил

2023-11-23 17:46 UTC, NemkovYaroslav commented on Sandbox/src/Sandbox.cpp
> +		: Application({ "Sandbox", 1200, 1200, args})
Исправил

2023-11-23 17:49 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +                if (ImGui::BeginCombo("Collider Type", currentColliderTypeString))
Не могу, у меня там доп логика висит на edit и на runtime мод

2023-11-24 05:06 UTC, mrLegenius commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +            if (ImGui::BeginCombo("Rigidbody Type", currentRigidbodyTypeString))
Можешь. DrawComboBox возвращает бул, поменялось ли значение.

2023-11-24 05:09 UTC, mrLegenius commented on LevEngine/src/Renderer/DebugRender/DebugRender.cpp
> +    void DebugRender::DrawWireCube(Matrix model, const Color color)
Мы ее не изменяем тут, поэтому должна быть конст, можно и ссылкой сделать

2023-11-24 05:11 UTC, mrLegenius commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +                EditorGUI::DrawFloatControl("Restitution", BindGetter(&Rigidbody::GetRestitution, &component), BindSetter(&Rigidbody::SetRestitution, &component), 1.0f, 0.0f, 1.0f);
Эти параметры не пренадлежат ригидбоди, а пренадлежат коллайдерам. Ладно, в другой таске поправишь

2023-11-24 05:15 UTC, mrLegenius commented on LevEditor/src/GUI/Drawers/Components/RigidbodyDrawer.cpp
> +                            if (component.IsInitialized())
Почему ты меняешь коллайдер при смене типа? Нехорошо.

2023-11-24 05:17 UTC, mrLegenius commented on LevEditor/src/GUI/Drawers/Components/RigidbodyDrawer.cpp
> +                            }
Если просто вызывать SetRigidbody из кода, дополнительно ВСЕГДА придется вызывать еще и AttaсhRigidbody? Тоже плохо. Засунь attach во внутрь компонента

2023-11-24 08:37 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +            if (ImGui::BeginCombo("Rigidbody Type", currentRigidbodyTypeString))
Исправил

2023-11-24 08:38 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +                if (ImGui::BeginCombo("Collider Type", currentColliderTypeString))
Исправил

2023-11-24 08:38 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/PhysicsDrawer.cpp
> +                EditorGUI::DrawFloatControl("Restitution", BindGetter(&Rigidbody::GetRestitution, &component), BindSetter(&Rigidbody::SetRestitution, &component), 1.0f, 0.0f, 1.0f);
Договорились

2023-11-24 08:44 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/RigidbodyDrawer.cpp
> +                            if (component.IsInitialized())
1. Ещё не реализовал возможность прикреплять Rigidbody с 0 Collider'ов.
2. Ещё не реализовал полноценное запоминание инфы о прошлом прикрепленном Collider'е.
Тематически относится к возможности прикрепления множества коллайдеров. Предлагают отложить до следующей таски.

2023-11-24 09:40 UTC, NemkovYaroslav commented on LevEngine/LevEngine.vcxproj
> +      <RuntimeLibrary>MultiThreadedDebugDll</RuntimeLibrary>
Исправил

2023-11-24 09:40 UTC, NemkovYaroslav commented on LevEngine/LevEngine.vcxproj
> +      <RuntimeLibrary>MultiThreadedDebugDll</RuntimeLibrary>
Исправил

2023-11-24 09:43 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.cpp
> +            DetachCollider();
Договорились

2023-11-24 09:47 UTC, NemkovYaroslav commented on LevEngine/src/Renderer/DebugRender/DebugRender.cpp
> +    void DebugRender::DrawWireCube(Matrix model, const Color color)
Исправил

2023-11-24 09:51 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Components/Rigidbody.h
> +        void SetRestitution(const float restitution);
В следующей таске вместе с материалами сделаю

2023-11-24 11:21 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Physics.h
> +        [[nodiscard]] static Physics& GetInstance();
Исправил

2023-11-24 11:43 UTC, NemkovYaroslav commented on LevEngine/src/Physics/Physics.h
> +        [[nodiscard]] static Physics& GetInstance();
Исправил

2023-11-24 12:25 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/RigidbodyDrawer.cpp
> +                            }
Исправил

2023-11-24 13:16 UTC, NemkovYaroslav commented on LevEngine/src/Scene/Systems/Physics/RigidbodyUpdateSystem.cpp
> +    }
Исправил

2023-11-24 13:25 UTC, NemkovYaroslav commented on LevEditor/src/GUI/Drawers/Components/RigidbodyDrawer.cpp
> +                            if (component.IsInitialized())
3. Это проблема сейчас только в Play Mode'е. В Edit Mode'е всё сохраняется.

2023-11-24 13:34 UTC, merged